# Generated by Django 3.1.2 on 2020-10-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lesson_lesson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_id',
            field=models.IntegerField(unique=True),
        ),
    ]
