# Generated by Django 3.1.2 on 2020-10-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201026_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_content',
            field=models.TextField(default='Content'),
        ),
    ]
