# Generated by Django 3.1.2 on 2020-10-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201026_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_content',
            field=models.TextField(default='Content'),
        ),
    ]
