# Generated by Django 3.1.2 on 2020-10-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201030_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_description',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
