# Generated by Django 3.1.2 on 2020-11-03 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201103_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 3, 16, 59, 55, 660812, tzinfo=utc)),
        ),
    ]
