# Generated by Django 3.1.4 on 2020-12-16 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201103_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 16)),
        ),
    ]
